---
- name: Deploy Nginx and WordPress in Docker
  hosts: all
  become: yes
  tasks:
  
    - name: Install Docker Python library
      ansible.builtin.pip:
        name: docker
        state: present
        
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if Docker network exists
      command: docker network inspect wordpress_network
      register: network_check
      ignore_errors: yes

    - name: Create a Docker network
      command: docker network create wordpress_network
      when: network_check.rc != 0

    - name: Create a directory for persistent WordPress data
      file:
        path: /opt/wordpress_data
        state: directory

    - name: Launch MySQL container
      docker_container:
        name: mysql_db
        image: mysql:5.7
        state: started
        restart_policy: unless-stopped
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ wordpress_db_name }}"
          MYSQL_USER: "{{ wordpress_db_user }}"
          MYSQL_PASSWORD: "{{ wordpress_db_password }}"
        volumes:
          - /opt/wordpress_data/mysql:/var/lib/mysql
        networks:
          - name: wordpress_network
 


    - name: Create a directory for persistent Nginx data
      file:
        path: /opt/nginx_data
        state: directory

    - name: Launch Nginx container
      command: >
        docker run
        -d
        --name nginx_server
        --network wordpress_network
        --restart=always
        -p 0.0.0.0:80:80
        -v /opt/nginx_data:/etc/nginx/conf.d
        nginx:latest

    - name: Launch WordPress container
      docker_container:
        name: "{{ wordpress_app_name }}"
        image: wordpress:latest
        state: started
        restart_policy: unless-stopped
        env:
          WORDPRESS_DB_HOST: "mysql_db"
          WORDPRESS_DB_NAME: "{{ wordpress_db_name }}"
          WORDPRESS_DB_USER: "{{ wordpress_db_user }}"
          WORDPRESS_DB_PASSWORD: "{{ wordpress_db_password }}"
        volumes:
          - /opt/wordpress_data/html:/var/www/html
        networks:
          - name: wordpress_network
        
